// =====================================================================
//  DO NOT EDIT THIS FILE
// Edit branding.ts instead
// =====================================================================

import { brandConfig, siteConfig, socialLinks, navbarConfig, mobileMenuConfig, footerConfig } from "./branding";

// Re-export user configs
export { brandConfig, siteConfig, socialLinks, navbarConfig, mobileMenuConfig, footerConfig };

// Logo config for navbar and footer
export const brandingConfig = {
  name: siteConfig.name,
  navbar: {
    logoType: navbarConfig.logo.type === "text" ? "text-only" : navbarConfig.logo.type === "image" ? "logo-only" : "logo-text",
    logoImage: navbarConfig.logo.image,
    logoWidth: navbarConfig.logo.imageSize,
    logoHeight: navbarConfig.logo.imageSize,
    text: navbarConfig.logo.text,
    textClassName: "text-2xl font-bold text-white tracking-tight hover:text-brand transition-colors",
    customLogo: null,
    logoTextGap: "gap-3",
  },
  footer: {
    logoType: footerConfig.logo.type === "text" ? "text-only" : footerConfig.logo.type === "image" ? "logo-only" : footerConfig.logo.type === "none" ? "none" : "logo-text",
    logoImage: footerConfig.logo.image,
    logoWidth: footerConfig.logo.imageSize,
    logoHeight: footerConfig.logo.imageSize,
    text: footerConfig.logo.text,
    description: footerConfig.description,
    email: siteConfig.emails.contact,
    textClassName: footerConfig.logo.gradient 
      ? "bg-gradient-to-r from-brand/80 via-brand to-brand/90 bg-clip-text text-transparent text-2xl font-bold tracking-tight"
      : "text-2xl font-bold text-white tracking-tight",
    customLogo: null,
    logoTextGap: "gap-2",
  },
  copyright: siteConfig.copyright,
  emails: siteConfig.emails,
} as const;

// Navbar links (center menu)
export const navbarLinks = navbarConfig.links;

// Navbar buttons (right side)
export const navbarButtons = navbarConfig.buttons;

// Mobile menu
export const mobileNavSections = mobileMenuConfig.sections;
export const mobileNavButtons = mobileMenuConfig.buttons;

// Footer columns
export const footerColumns = footerConfig.columns.map(col => ({
  title: col.title,
  items: col.links.map(link => ({ title: link.name, href: link.href })),
}));

// Footer bottom bar
export const footerBottomBar = {
  links: footerConfig.bottomLinks,
  disclaimers: [footerConfig.disclaimer],
};
